# Generated by Django 4.2.7 on 2026-04-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_configuracaoempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaoempresa',
            options={},
        ),
        migrations.RemoveField(
            model_name='configuracaoempresa',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='configuracaoempresa',
            name='chave',
        ),
        migrations.RemoveField(
            model_name='configuracaoempresa',
            name='valor',
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='email',
            field=models.CharField(default='comercial@grupack.com.br', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='endereco',
            field=models.CharField(default='Rua 15 de Novembro, N 1206 - Marilia - SP', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='header_subtitulo',
            field=models.CharField(default='Qualidade e agilidade na entrega', max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='header_titulo',
            field=models.CharField(default='📦 Catálogo de Produtos', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='horario',
            field=models.CharField(default='Segunda à Sexta: 8h às 18h', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='mensagem_padrao',
            field=models.TextField(default='Olá! Vi o produto {produto} no catálogo.'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='nome',
            field=models.CharField(default='Alpack Distribuidora', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='whatsapp',
            field=models.CharField(default='551434340001', max_length=20),
        ),
    ]
